support to assemble and run  *.war

diff --git a/spring-boot/springboot-sti/.sti/bin/assemble b/spring-boot/springboot-sti/.sti/bin/assemble
--- a/spring-boot/springboot-sti/.sti/bin/assemble
+++ b/spring-boot/springboot-sti/.sti/bin/assemble
@@ -42,6 +42,7 @@ function copy_artifacts() {
   if [ -d $LOCAL_SOURCE_DIR/$1 ]; then
     echo "Copying all JAR artifacts from $LOCAL_SOURCE_DIR/$1 directory into $DEPLOY_DIR for later deployment..."
     cp -v $LOCAL_SOURCE_DIR/$1/*.jar $DEPLOY_DIR 2> /dev/null
+    cp -v $LOCAL_SOURCE_DIR/$1/*.war $DEPLOY_DIR 2> /dev/null
   fi
 }
 
@@ -135,6 +136,10 @@ if [ $(ls /opt/openshift/*.jar | wc -l) -eq 1 ]; then
   mv /opt/openshift/*.jar /opt/openshift/app.jar
   [ ! -f /opt/openshift/app.jar ] && echo "Application could not be properly built." && exit 1 
   echo "Application jar file is located in /opt/openshift/app.jar"
+elif [ $(ls /opt/openshift/*.war | wc -l) -eq 1 ]; then
+  mv /opt/openshift/*.war /opt/openshift/app.war
+  [ ! -f /opt/openshift/app.war ] && echo "Application could not be properly built." && exit 1 
+  echo "Application jar file is located in /opt/openshift/app.war"
 else
   exit 1
 fi
diff --git a/spring-boot/springboot-sti/.sti/bin/run b/spring-boot/springboot-sti/.sti/bin/run
--- a/spring-boot/springboot-sti/.sti/bin/run
+++ b/spring-boot/springboot-sti/.sti/bin/run
@@ -7,4 +7,10 @@
 #	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
 #
 
-exec java -Djava.security.egd=file:/dev/./urandom -jar /opt/openshift/app.jar $APP_OPTIONS
+if [ $(ls /opt/openshift/app.jar | wc -l) -eq 1 ]; then
+    exec java -Djava.security.egd=file:/dev/./urandom -jar /opt/openshift/app.jar $APP_OPTIONS
+elif [ $(ls /opt/openshift/app.war | wc -l) -eq 1 ]; then
+    exec java -Djava.security.egd=file:/dev/./urandom -jar /opt/openshift/app.war $APP_OPTIONS
+else
+    echo "Could not launch application due to /opt/openshift/app.jar or app.war does not exist" && exit 1
+fi
